TournamentApp/config/routes.rb
TournamentApp::Application.routes.draw do
 
  # resources :posts


root "events#home" 

 
resources :users
resources :sessions
resources :registrations
resources :games

 post '/login' => 'users#login'

get "/logout" => "sessions#destroy", as: 'logout'

resources :events

resources :tournaments

resources :characters


resources :players


resources :pools 

resources :posts do
    resources :comments, :only => [:create]
  end

  # root :to => 'welcome#index'







end

TournamentApp/app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	validates :name, uniqueness: true 
	validates :email, uniqueness: { scope: :email,
    message: "Sorry, another user has this email." }

	has_many :registrations, :dependent => :destroy

 protected 
  	after_destroy do |user|
		puts "User purged from database"  
	end
end

TournamentApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
def show
    @user = User.find(params[:id])
    if session[:user_id] != @user.id
      redirect_to root_url, notice: "No way!"
  end
end
  
def create
    user = User.new
    user.name = params[:name]
    user.email = params[:email]
    user.password = params[:password]
    user.password_confirmation = params[:password]
    if user.save
      UserMailer.welcome_email(user).deliver
    	session[:user_id] = user.id
    	redirect_to root_url, notice: "Thanks for signing up!" and return
    else
      redirect_to new_user_path, notice: "Sorry, another user has this email." and return
	end 
end



 
end

TournamentApp/app/helpers/users_helper.rb
module UsersHelper
end

TournamentApp/app/views/users/new.html.erb
<h1>Sign Up!</h1>

<% if notice.present? %>
 <%= notice %>
 <% end %> 

<%= form_tag "/users" do %>

  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <br>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <br>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <br>
  <%= submit_tag "Sign Me Up!" %>

<% end %>

TournamentApp/app/views/users/show.html.erb
<h1> <%= @user.name %>'s Profile</h1>

<p> View your current tournament entries: <%= link_to "View My Register!", registrations_path %> </p>
<br>

<p> View your current tournament pools: <%= link_to "View My Pools!", pool_path %> </p>

<br>
<p> View your opponents tournament pools: <%= link_to "View Rivals in Pools!", pools_path %> </p>
<br>
<p> If you have not registered click here:
<%= link_to "Register!", new_registration_path %> </p>