TournamentApp/config/routes.rb
TournamentApp::Application.routes.draw do
 
  # resources :posts


root "events#home" 

 
resources :users
resources :sessions
resources :registrations
resources :games

 post '/login' => 'users#login'

get "/logout" => "sessions#destroy", as: 'logout'

resources :events

resources :tournaments

resources :characters


resources :players


resources :pools 

resources :posts do
    resources :comments, :only => [:create]
  end

  # root :to => 'welcome#index'







end

TournamentApp/app/models/pool.rb
class Pool < ActiveRecord::Base

	has_many :assigns, :dependent => :destroy
	has_many :players, :through => :assigns, :dependent => :destroy
	has_many :players,:dependent => :destroy
	validates :player_id, :presence => true


	belongs_to :players
	belongs_to :game




protected
after_find do |pool|
    puts "You have found a pool object!"
  end
end

TournamentApp/app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  helper_method :sort_column, :sort_direction

	before_action :require_login, :except => [:home, :login]
    before_action :identify_user

    def identify_user
      user = User.find_by(id: session[:user_id])
      if user
        @username = user.name
      end
    end

    def require_login
      if session[:user_id].blank?
        redirect_to root_url, notice: "Need to Sign Up to view this feature"
      end
    end

    def logout
      reset_session
      redirect_to root_url
    end

    def login
      session[:id] = params[:name]
      redirect_to root_url
    end
    
	def index
	
	 @pools = Pool.all.order(sort_column + " " + sort_direction)
    # @pools = Tournament.where(:user_id => params[:id])

	end
    private
  
  def sort_column
    Pool.column_names.include?(params[:sort]) ? params[:sort] : "game_id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

	def show
    # p  = params["id"]
    @pool = Tournament.where(:user_id => params['id'])

     # @pools = Pool.all.order(sort_column + " " + sort_direction)

   end

	def destroy
    the_pool_id = params["id"]
    p = Pool.find_by(:id => the_pool_id)
    p.destroy
    redirect_to pools_url
    end

	# def new 
 #    @pool = Pool.all
	# end

	
	
end

TournamentApp/app/views/pools/index.html.erb
<h1 class="page-header"> <%= @username %>'s Pools</h1>

<h2> View all Characters in Tournaments</h2>

<table>
	<tr>
  <th style="padding:0 15px 0 15px;"><%= sortable "Game: Character" %></th>
</tr>
				</table>


<% @pools.each do |pol| %>
     <% @check = pol.game_id %>
    <% @chk = Game.find(@check).name  %>
     <% @t = Character.where(:name => @chk).sample(2) %>
    <% @t.each do |rope| %>
    <div class="col-md-15">
	  <%= rope.name + ':' %> 



    <%= rope.character %>


      <%= image_tag rope.image_url, class: "img-responsive" %>

       <% end %>
<% end %>


     <%= link_to "View Your Pools' Character", pool_url(session[:user_id]),  class: 'navbar-brand' %> 




 <%= link_to "Back To My Profile", user_url(session[:user_id]),  class: 'navbar-brand' %> 

TournamentApp/app/views/pools/show.html.erb
<h1 class="page-header"> <%= @username %>'s Pools</h1>

<h2> Character choices random population</h2>




   <% @pool = Tournament.where(:user_id => params['id']) %>


<table>
  <tr>
    <th style="padding:0 15px 0 15px;">Game Character </th>

    </tr>

        </table>

</tr>

 
<% @pool.each do |pol| %>
  <tr>
     <% @check = pol.game_id %>

      <% @chk = Game.find(@check).name  %>

    <td> <% @t = Character.where(:name => @chk).sample(2) %></td>

       <% @t.each do |rope| %>
           <div class="col-md-15">

         <td><%= rope.name %></td>

             <div class="center">


       <td><%= rope.character %></td>

           <div class="right">

       <td > <%= image_tag rope.image_url, :class => :image_responsive %> </td>

       <% end %>
   
<% end %>

    </table>


 <%= link_to "Back To My Profile", user_url(session[:user_id]),  class: 'navbar-brand' %> 