TournamentApp/config/routes.rb
TournamentApp::Application.routes.draw do
 
  # resources :posts


root "events#home" 

 
resources :users
resources :sessions
resources :registrations
resources :games

 post '/login' => 'users#login'

get "/logout" => "sessions#destroy", as: 'logout'

resources :events

resources :tournaments

resources :characters


resources :players


resources :pools 

resources :posts do
    resources :comments, :only => [:create]
  end

  # root :to => 'welcome#index'







end

TournamentApp/app/models/assign.rb
class Assign < ActiveRecord::Base
  belongs_to :player
  belongs_to :pool
end

TournamentApp/app/models/character.rb
class Character < ActiveRecord::Base

	has_many :features
	has_many :tournaments, :through => :features
	# belongs_to :game 
	

end

TournamentApp/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

TournamentApp/app/models/event.rb
class Event < ActiveRecord::Base

	# has_many :tournaments, :dependent => :destroy
	# has_many :registrations, :dependent => :destroy
 
end

TournamentApp/app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :tournament
  validates :tournament, :presence => true
  belongs_to :character
end

TournamentApp/app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :tournament
	has_many :registrations, :dependent => :destroy
	has_many :pools, :dependent => :destroy
	# has_many :characters, :dependent => :destroy


end

TournamentApp/app/models/player.rb
class Player < ActiveRecord::Base
has_many :assigns
has_many :tourney_entries, :dependent => :destroy
has_many :tournaments, :through => :tourney_entries, :dependent => :destroy
has_many :pools, :dependent => :destroy
belongs_to :tournament
validates :registration_id, :presence => true
 belongs_to :pool

	
end

# heroku create 

TournamentApp/app/models/pool.rb
class Pool < ActiveRecord::Base

	has_many :assigns, :dependent => :destroy
	has_many :players, :through => :assigns, :dependent => :destroy
	has_many :players,:dependent => :destroy
	validates :player_id, :presence => true


	belongs_to :players
	belongs_to :game




protected
after_find do |pool|
    puts "You have found a pool object!"
  end
end

TournamentApp/app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :body, :title
	has_many :comments


	# searchable do
 #  		text :body
 #  		text :title
  
 #  	end
  
end

TournamentApp/app/models/registration.rb
class Registration < ActiveRecord::Base

	 belongs_to :user
	 belongs_to :game
	 has_many :tourney_entries, :dependent => :destroy
	 has_many :players, :through => :tourney_entries, :dependent => :destroy
	 has_many :tournaments, :through => :tourney_entries, :dependent => :destroy
	 has_many :players, :dependent => :destroy
	 has_many :tournaments, :dependent => :destroy
	 validates_length_of :name, :within => 6..20, :too_long => "pick a shorter name", :too_short => "pick a longer name"
	 validates_length_of :gamertag, :within => 6..20, :too_long => "pick a shorter name", :too_short => "pick a longer name"
	 validates_presence_of :address
	 validates_presence_of :game

protected
 after_save do |registration|
    puts "You have saved a registration!"
  end
end

TournamentApp/app/models/tournament.rb
class Tournament < ActiveRecord::Base

 belongs_to :game
 belongs_to :registration
 validates :registration_id, :presence => true
 belongs_to :player
 belongs_to :user
 has_many :features, :dependent => :destroy
 has_many :tourney_entries, :dependent => :destroy
 has_many :characters, :through => :features, :dependent => :destroy

 
end

TournamentApp/app/models/tourney_entry.rb
class TourneyEntry < ActiveRecord::Base
   belongs_to :tournament
   belongs_to :player
   belongs_to :pool
   belongs_to :registration
   validates :registration_id, :presence => true

end

TournamentApp/app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	validates :name, uniqueness: true 
	validates :email, uniqueness: { scope: :email,
    message: "Sorry, another user has this email." }

	has_many :registrations, :dependent => :destroy

 protected 
  	after_destroy do |user|
		puts "User purged from database"  
	end
end

TournamentApp/app/controllers/games_controller.rb
class GamesController < ApplicationController
	
def index
		@games = Game.all.order("name asc")
	end

	def show 
		the_game_id = params["id"]
		@game = Game.find_by :id => the_game_id
	end

	def destroy
    the_game_id = params["id"]
    g= Game.find_by(:id => the_game_id)
    g.destroy
    redirect_to games_url
    end

	def new 
	end

	def create 
		g = game.new
		g.rules = params["rules"]
		g.game = params["game"]
		g.image = params["image"]
		e.save
		redirect_to games_url
	end

	def edit
		the_game_id = params["id"]
		@game = Game.find_by(:id => the_game_id)
	end

	def update
	    the_game_id = params["id"]
	    game = Game.find_by(:id => the_game_id)
	    game.game = params["game"]
	    g.rules = params["rules"]
	    game.image = params["image"]
	    game.save
	    redirect_to games_url
	end	
end

TournamentApp/app/helpers/application_helper.rb
module ApplicationHelper


def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, {:sort => column, :direction => direction}, {:class => css_class}
end

end

TournamentApp/app/helpers/comments_helper.rb
module CommentsHelper
end

TournamentApp/app/helpers/games_helper.rb
module GamesHelper
end

TournamentApp/app/helpers/posts_helper.rb
module PostsHelper
end

TournamentApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

TournamentApp/app/helpers/users_helper.rb
module UsersHelper
end

TournamentApp/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

TournamentApp/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>    
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

TournamentApp/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>


 <%= link_to 'Event', root_path, class: 'navbar-brand' %>
  <%= link_to 'Tournaments', games_url, class: 'navbar-brand' %>      

 <%= link_to 'Pools', pools_url, class: 'navbar-brand' %>
<%= link_to 'Post Comments', posts_url, class: 'navbar-brand' %>


   

 <% if session[:user_id].blank? %>
    <%= link_to "Sign Up", new_user_url, class: 'navbar-brand' %>
     <%= link_to "Sign In", new_session_url,  class: 'navbar-brand' %>


 <% elsif session[:registration_id].blank? %>
      <%= link_to " New Registration", new_registration_path,  class: 'navbar-brand' %>

       <%= link_to "My Profile", user_url(session[:user_id]),  class: 'navbar-brand' %>
       
       <%= link_to "Sign Out", logout_url ,  class: 'navbar-brand'%>
      

       
  <% end %>

<!-- registration_url(session[:user_id]) -->

TournamentApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tournament App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tournament App" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>


       <%= yield %>
    </main>

    
  </body>
</html>